feat: docker deploy test

diff --git a/.github/workflows/deploy-with-docker.yml b/.github/workflows/deploy-with-docker.yml
--- a/.github/workflows/deploy-with-docker.yml
+++ b/.github/workflows/deploy-with-docker.yml
@@ -1,4 +1,4 @@
-name: Deploy with Docker
+name: Test and Deploy with Docker
 
 on:
   push:
@@ -33,8 +33,31 @@ jobs:
           username: ${{ secrets.REGISTRY_USERNAME }}
           password: ${{ secrets.REGISTRY_PASSWORD }}
 
-      - name: Build then Deploy
+      - name: Build Docker Image
         run: |
-          docker build -t apisixacr.azurecr.cn/dashboard:${{ github.sha }} .
+          docker build -t dashboard:ci .
+
+      - name: Modify ETCD IP
+        run: |
+          sed -i 's/127.0.0.1:2379/172.16.238.10:2379/' api/conf/conf.yaml
+
+      - name: Run Docker Compose
+        working-directory: ./api/test/docker-deploy
+        run: |
+          docker-compose up -d
+          sleep 5
+          docker logs docker-deploy_managerapi_1
+
+      - name: Run Test
+        run: |
+          curl http://127.0.0.1:8088/apisix/admin/user/login -X POST -i -d '{"username":"admin", "password": "admin"}'
+          code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:8088/apisix/admin/user/login -X POST -i -d '{"username":"admin", "password": "admin"}')
+          if [ ! $code -eq 200 ]; then
+              echo "failed: failed to custom port"
+              exit 1
+          fi
+
+      - name: Deploy
+        run: |
+          docker tag dashboard:ci apisixacr.azurecr.cn/dashboard:${{ github.sha }}
           docker push apisixacr.azurecr.cn/dashboard:${{ github.sha }}
-          docker run -d -p 80:8080 -v ${pwd}/docs/examples/docker-conf-example.json:/usr/local/apisix-dashboard/conf/conf.json apisixacr.azurecr.cn/dashboard:${{ github.sha }}
