test: add test case

diff --git a/.github/workflows/test-api.yml b/.github/workflows/test-api.yml
--- a/.github/workflows/test-api.yml
+++ b/.github/workflows/test-api.yml
@@ -49,3 +49,19 @@ jobs:
         run: |
           export APIX_ETCD_ENDPOINTS=127.0.0.1:2379
           go test ./...
+
+      - name: run with custom port
+        working-directory: ./api
+        run: |
+          export APIX_ETCD_ENDPOINTS=127.0.0.1:2379
+          sed  -i 's/8080/\# 8088/'  conf/config.yaml
+          go run main.go &
+
+      - name: run with custom port
+        working-directory: ./api
+        run: |
+          code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:8088/apisix/admin/user/login -X PUT -i -d '{"username":"admin", "password": "admin"}')
+          if [ ! $code -eq 200 ]; then
+              echo "failed: failed to custom port"
+              exit 1
+          fi
